name: mynas_manager
description: MyNAS Manager - A user-friendly management interface for TrueNAS SCALE
license: AGPL-3.0
publish_to: none

workspace:
  - backend
  - frontend
  - shared
  - mynas_desktop

environment:
  sdk: ^3.8.1

dev_dependencies:
  dart_pre_commit: ^5.4.6

# Pre-commit hook configuration
dart_pre_commit:
  # Format all Dart/Flutter files
  format:
    line-length: 80

  # Run static analysis
  analyze: true

  # Scan for security vulnerabilities
  osv_scanner: true
