name: truenas_client
description: TrueNAS SCALE API client library for Dart
version: 1.0.0
license: AGPL-3.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.8.1

dependencies:
  # Core dependencies
  json_rpc_2: ^4.0.0
  web_socket_channel: ^3.0.1
  stream_channel: ^2.1.2
  dio: ^5.7.0
  logging: ^1.3.0
  
  # Model dependencies
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
  mockito: ^5.4.4
  build_runner: ^2.4.9
  freezed: ^3.1.0
  json_serializable: ^6.8.0
