name: mynas_desktop
description: A reusable desktop window management system for Flutter web
version: 0.1.0
license: AGPL-3.0
resolution: workspace

environment:
  sdk: ^3.8.1
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  flutter_box_transform: ^0.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
